# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    packages:
      - python3-pip

dist:
  - trusty

matrix:
  include:
    # Linux {

    # Release {

    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc
    - os: linux
      env: CONFIG=Release TOOLCHAIN=android-ndk-r15c-api-21-armeabi-v7a-neon-clang-libcxx
    - os: linux
      env: CONFIG=Release TOOLCHAIN=analyze

    # }

    # Debug {

    - os: linux
      env: CONFIG=Debug TOOLCHAIN=gcc
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=android-ndk-r15c-api-21-armeabi-v7a-neon-clang-libcxx
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=analyze

    # }

    # }

    # OSX {

    # Release {

    - os: osx
      env: CONFIG=Release TOOLCHAIN=libcxx
    - os: osx
      env: CONFIG=Release TOOLCHAIN=osx-10-11
    - os: osx
      env: CONFIG=Release TOOLCHAIN=ios-nocodesign-9-3

    # }

    # Debug {

    - os: osx
      env: CONFIG=Debug TOOLCHAIN=libcxx
    - os: osx
      env: CONFIG=Debug TOOLCHAIN=osx-10-11
    - os: osx
      env: CONFIG=Debug TOOLCHAIN=ios-nocodesign-9-3

    # }

    # }

install:
  # Info about OS
  - uname -a

  # Disable autoupdate
  # * https://github.com/Homebrew/brew/blob/7d31a70373edae4d8e78d91a4cbc05324bebc3ba/Library/Homebrew/manpages/brew.1.md.erb#L202
  - export HOMEBREW_NO_AUTO_UPDATE=1

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then travis_retry pip3 install --user requests; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - export POLLY_ROOT="`pwd`/polly-master"
  - export PATH="${POLLY_ROOT}/bin:${PATH}"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"
  - export ANDROID_NDK_r11c="`pwd`/_ci/android-ndk-r11c"
  - export ANDROID_NDK_r15c="`pwd`/_ci/android-ndk-r15c"

script:
  - python3 ./run-test.py --toolchain ${TOOLCHAIN} --type ${CONFIG}

# https://docs.travis-ci.com/user/customizing-the-build/#Whitelisting-or-blacklisting-branches
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - /^pr\..*/
